/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as presaleSol from "./Presale.sol";
export { PresaleManager__factory } from "./PresaleManager__factory";
