/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  PresaleManager,
  PresaleManagerInterface,
} from "../PresaleManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_presaleAddress",
        type: "address",
      },
    ],
    name: "addPresale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
    ],
    name: "getPresale",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a0806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806377ce88eb1461003b5780637f59b0441461006b575b600080fd5b610055600480360381019061005091906101d3565b610087565b604051610062919061020f565b60405180910390f35b6100856004803603810190610080919061022a565b6100ef565b005b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169050919050565b806000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101a082610175565b9050919050565b6101b081610195565b81146101bb57600080fd5b50565b6000813590506101cd816101a7565b92915050565b6000602082840312156101e9576101e8610170565b5b60006101f7848285016101be565b91505092915050565b61020981610195565b82525050565b60006020820190506102246000830184610200565b92915050565b6000806040838503121561024157610240610170565b5b600061024f858286016101be565b9250506020610260858286016101be565b915050925092905056fea264697066735822122013930bc314a7c40b6a17b4688abda9994a939cec6a4bbb3a8aecc1bb92c0e7f364736f6c63430008180033";

type PresaleManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PresaleManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PresaleManager__factory extends ContractFactory {
  constructor(...args: PresaleManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PresaleManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PresaleManager__factory {
    return super.connect(runner) as PresaleManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PresaleManagerInterface {
    return new Interface(_abi) as PresaleManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PresaleManager {
    return new Contract(address, _abi, runner) as unknown as PresaleManager;
  }
}
