/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as presaleSol from "./Presale.sol";
export type { presaleSol };
export type { PresaleManager } from "./PresaleManager";
export * as factories from "./factories";
export type { IERC20 } from "./Presale.sol/IERC20";
export { IERC20__factory } from "./factories/Presale.sol/IERC20__factory";
export type { Presale } from "./Presale.sol/Presale";
export { Presale__factory } from "./factories/Presale.sol/Presale__factory";
export { PresaleManager__factory } from "./factories/PresaleManager__factory";
